baseURL = "https://text.ytkhs.dev"
defaultContentLanguage = "ja"
disableHugoGeneratorInject = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "ja-JP"
paginate = 10
publishDir = "public"
rssLimit = 10
theme = "default"
title = "text.ytkhs.dev"

[menu]

# [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 1

[params]
author = "ytkhs"
faviconChar = "👾"
#description = ""
images = [
    #'images/og-featured.png' # relative path to "static" directory
]
customCSS = [
    #'css/my.css' # relative path to "assets" directory
]
customJS = [
    #'js/main.js' # relative path to "assets" directory
]
dateFormat = '2006-01-02 15:04'
paginationSinglePost = true
readMore = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = [ "RSS", "HTML"]
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"