baseURL = "https://ytkhs.me/"
DefaultContentLanguage = "ja"
languageCode = "ja-JP"
title = "ytkhs.me on github.io"
theme = "anubis"
publishDir = "docs" # for github pages
paginate = 10
enableRobotsTXT = true

[menu]

# [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 1

[params]
author = "ytkhs"
#description = ""
images = [
    #'images/og-featured.png' # relative path to "static" directory
]
customCSS = [
    #'css/my.css' # relative path to "assets" directory
]
customJS = [
    #'js/main.js' # relative path to "assets" directory
]
dateFormat = '2006-01-02 15:04'
paginationSinglePost = true
style = 'light-without-switcher'
readMore = true