baseURL = "https://note.ytkhs.me"
defaultContentLanguage = "ja"
languageCode = "ja-JP"
title = "note.ytkhs.me"
theme = "anubis"
publishDir = "public"
paginate = 10
enableRobotsTXT = false
enableEmoji = true
disableHugoGeneratorInject = true
hasCJKLanguage = true
rssLimit = 10

[menu]

# [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 1

[params]
author = "ytkhs"
#description = ""
images = [
    #'images/og-featured.png' # relative path to "static" directory
]
customCSS = [
    #'css/my.css' # relative path to "assets" directory
]
customJS = [
    #'js/main.js' # relative path to "assets" directory
]
dateFormat = '2006-01-02 15:04'
paginationSinglePost = true
style = 'light-without-switcher'
readMore = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = [ "RSS", "HTML"]
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"